-- Generated by Oracle SQL Developer Data Modeler 4.1.3.901
--   at:        2017-10-12 20:02:41 MSK
--   site:      SQL Server 2012
--   type:      SQL Server 2012




CREATE
  TABLE Address
  (
    id UNIQUEIDENTIFIER NOT NULL ,
    postcode      VARCHAR ,
    city          VARCHAR ,
    street        VARCHAR ,
    street_number VARCHAR ,
    district      VARCHAR ,
    building      VARCHAR ,
    apprtment     VARCHAR
  )
  ON "default"
GO
ALTER TABLE Address ADD CONSTRAINT Address_PK PRIMARY KEY CLUSTERED (id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Appeal
  (
    id UNIQUEIDENTIFIER NOT NULL ,
    user_id UNIQUEIDENTIFIER ,
    type AppealType ,
    description  VARCHAR ,
    rating       INTEGER ,
    created_date DATETIME ,
    Object_code UNIQUEIDENTIFIER NOT NULL
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
Appeal__IDX ON Appeal
(
  Object_code
)
ON "default"
GO
ALTER TABLE Appeal ADD CONSTRAINT Appeal_PK PRIMARY KEY CLUSTERED (id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Car
  (
    id UNIQUEIDENTIFIER NOT NULL ,
                     NUMBER VARCHAR ,
    capacity         VARCHAR ,
    start_using_date DATETIME ,
    end_using_date   DATETIME
  )
  ON "default"
GO
ALTER TABLE Car ADD CONSTRAINT Car_PK PRIMARY KEY CLUSTERED (id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE DeliveryAttributes
  (
    id UNIQUEIDENTIFIER NOT NULL ,
    check_number VARCHAR ,
    Summary_id UNIQUEIDENTIFIER NOT NULL
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
DeliveryAttributes__IDX ON DeliveryAttributes
(
  Summary_id
)
ON "default"
GO
ALTER TABLE DeliveryAttributes ADD CONSTRAINT DeliveryAttributes_PK PRIMARY KEY
CLUSTERED (id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Exchange
  (
    id UNIQUEIDENTIFIER NOT NULL ,
    amount        DECIMAL (28) ,
    ordered_times INTEGER ,
    Nominals_id UNIQUEIDENTIFIER NOT NULL
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
Exchange__IDX ON Exchange
(
  Nominals_id
)
ON "default"
GO
ALTER TABLE Exchange ADD CONSTRAINT Exchange_PK PRIMARY KEY CLUSTERED (id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE ManRouteTimestampRelation
  (
    User_id UNIQUEIDENTIFIER NOT NULL ,
    RouteTimestamp_id UNIQUEIDENTIFIER NOT NULL
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
ManRouteTimestampRelation__IDX ON ManRouteTimestampRelation
(
  RouteTimestamp_id
)
ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
ManRouteTimestampRelation__IDXv1 ON ManRouteTimestampRelation
(
  User_id
)
ON "default"
GO


CREATE
  TABLE Nominals
  (
    id UNIQUEIDENTIFIER NOT NULL ,
    multiply_index DECIMAL (28) ,
    description    VARCHAR ,
    type NominalType ,
    weight BIGINT ,
    total DECIMAL (28)
  )
  ON "default"
GO
ALTER TABLE Nominals ADD CONSTRAINT Nominals_PK PRIMARY KEY CLUSTERED (id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Object
  (
    code UNIQUEIDENTIFIER NOT NULL ,
    state ObjectState ,
    object_type ObjectType ,
    description VARCHAR ,
    pass        VARCHAR ,
    Address_id UNIQUEIDENTIFIER NOT NULL
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
Object__IDX ON Object
(
  Address_id
)
ON "default"
GO
ALTER TABLE Object ADD CONSTRAINT Object_PK PRIMARY KEY CLUSTERED (code)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE ObjectAmountRelation
  (
    Summary_id UNIQUEIDENTIFIER NOT NULL ,
    DATE DATETIME NOT NULL ,
    Object_code UNIQUEIDENTIFIER NOT NULL
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
ObjectAmountRelation__IDX ON ObjectAmountRelation
(
  Object_code
)
ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
ObjectAmountRelation__IDXv1 ON ObjectAmountRelation
(
  Summary_id
)
ON "default"
GO


CREATE
  TABLE "Order"
  (
    id UNIQUEIDENTIFIER NOT NULL ,
    name         VARCHAR ,
    phone_number VARCHAR ,
                 DATE DATETIME ,
    description  VARCHAR ,
    Object_code UNIQUEIDENTIFIER NOT NULL ,
    User_id UNIQUEIDENTIFIER NOT NULL ,
    DeliveryAttributes_id UNIQUEIDENTIFIER NOT NULL
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
Order__IDX ON "Order"
(
  Object_code
)
ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
Order__IDXv1 ON "Order"
(
  User_id
)
ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
Order__IDXv2 ON "Order"
(
  DeliveryAttributes_id
)
ON "default"
GO
ALTER TABLE "Order" ADD CONSTRAINT Order_PK PRIMARY KEY CLUSTERED (id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE RouteTimestamp
  (
    id UNIQUEIDENTIFIER NOT NULL ,
    TIME DATETIME NOT NULL ,
    Car_id UNIQUEIDENTIFIER NOT NULL ,
    Address_id UNIQUEIDENTIFIER NOT NULL
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
RouteTimestamp__IDX ON RouteTimestamp
(
  Car_id
)
ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
RouteTimestamp__IDXv1 ON RouteTimestamp
(
  Address_id
)
ON "default"
GO
ALTER TABLE RouteTimestamp ADD CONSTRAINT RouteTimestamp_PK PRIMARY KEY
CLUSTERED (id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Session
  (
    id UNIQUEIDENTIFIER NOT NULL ,
    system_type SystemType ,
    start_time  DATETIME ,
    last_active DATETIME ,
    terminated BIT ,
    User_id UNIQUEIDENTIFIER NOT NULL
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
Session__IDX ON Session
(
  User_id
)
ON "default"
GO
ALTER TABLE Session ADD CONSTRAINT Session_PK PRIMARY KEY CLUSTERED (id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Settings
  (
    id UNIQUEIDENTIFIER NOT NULL ,
    session_id UNIQUEIDENTIFIER ,
    push_enabled UNIQUEIDENTIFIER ,
    show_closed_object BIT ,
    Session_id1 UNIQUEIDENTIFIER NOT NULL
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
Settings__IDX ON Settings
(
  Session_id1
)
ON "default"
GO
ALTER TABLE Settings ADD CONSTRAINT Settings_PK PRIMARY KEY CLUSTERED (id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Summary
  (
    id UNIQUEIDENTIFIER NOT NULL ,
    total_amount DECIMAL (28)
  )
  ON "default"
GO
ALTER TABLE Summary ADD CONSTRAINT Summary_PK PRIMARY KEY CLUSTERED (id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE SummaryExchangeRelation
  (
    Summary_id UNIQUEIDENTIFIER NOT NULL ,
    Exchange_id UNIQUEIDENTIFIER NOT NULL
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
SummaryExchangeRelation__IDX ON SummaryExchangeRelation
(
  Summary_id
)
ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
SummaryExchangeRelation__IDXv1 ON SummaryExchangeRelation
(
  Exchange_id
)
ON "default"
GO


CREATE
  TABLE "User"
  (
    id UNIQUEIDENTIFIER NOT NULL ,
    name         VARCHAR ,
    surname      VARCHAR ,
    passport     VARCHAR ,
    birthday     DATETIME ,
    phone_number VARCHAR ,
    email        VARCHAR ,
    pass_hash    VARCHAR ,
    user_type UserType
  )
  ON "default"
GO
ALTER TABLE "User" ADD CONSTRAINT User_PK PRIMARY KEY CLUSTERED (id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE UserObjectRelation
  (
    user_display_name VARCHAR NOT NULL ,
    User_id UNIQUEIDENTIFIER NOT NULL ,
    Object_code UNIQUEIDENTIFIER NOT NULL
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
UserObjectRelation__IDX ON UserObjectRelation
(
  User_id
)
ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
UserObjectRelation__IDXv1 ON UserObjectRelation
(
  Object_code
)
ON "default"
GO
ALTER TABLE UserObjectRelation ADD CONSTRAINT UserObjectRelation_PK PRIMARY KEY
CLUSTERED (User_id, Object_code)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

ALTER TABLE Appeal
ADD CONSTRAINT Appeal_Object_FK FOREIGN KEY
(
Object_code
)
REFERENCES Object
(
code
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE DeliveryAttributes
ADD CONSTRAINT DeliveryAttributes_Summary_FK FOREIGN KEY
(
Summary_id
)
REFERENCES Summary
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Exchange
ADD CONSTRAINT Exchange_Nominals_FK FOREIGN KEY
(
Nominals_id
)
REFERENCES Nominals
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE ManRouteTimestampRelation
ADD CONSTRAINT ManRouteTimestampRelation_RouteTimestamp_FK FOREIGN KEY
(
RouteTimestamp_id
)
REFERENCES RouteTimestamp
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE ManRouteTimestampRelation
ADD CONSTRAINT ManRouteTimestampRelation_User_FK FOREIGN KEY
(
User_id
)
REFERENCES "User"
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE ObjectAmountRelation
ADD CONSTRAINT ObjectAmountRelation_Object_FK FOREIGN KEY
(
Object_code
)
REFERENCES Object
(
code
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE ObjectAmountRelation
ADD CONSTRAINT ObjectAmountRelation_Summary_FK FOREIGN KEY
(
Summary_id
)
REFERENCES Summary
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Object
ADD CONSTRAINT Object_Address_FK FOREIGN KEY
(
Address_id
)
REFERENCES Address
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE "Order"
ADD CONSTRAINT Order_DeliveryAttributes_FK FOREIGN KEY
(
DeliveryAttributes_id
)
REFERENCES DeliveryAttributes
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE "Order"
ADD CONSTRAINT Order_Object_FK FOREIGN KEY
(
Object_code
)
REFERENCES Object
(
code
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE "Order"
ADD CONSTRAINT Order_User_FK FOREIGN KEY
(
User_id
)
REFERENCES "User"
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE RouteTimestamp
ADD CONSTRAINT RouteTimestamp_Address_FK FOREIGN KEY
(
Address_id
)
REFERENCES Address
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE RouteTimestamp
ADD CONSTRAINT RouteTimestamp_Car_FK FOREIGN KEY
(
Car_id
)
REFERENCES Car
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Session
ADD CONSTRAINT Session_User_FK FOREIGN KEY
(
User_id
)
REFERENCES "User"
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Settings
ADD CONSTRAINT Settings_Session_FK FOREIGN KEY
(
Session_id1
)
REFERENCES Session
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE SummaryExchangeRelation
ADD CONSTRAINT SummaryExchangeRelation_Exchange_FK FOREIGN KEY
(
Exchange_id
)
REFERENCES Exchange
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE SummaryExchangeRelation
ADD CONSTRAINT SummaryExchangeRelation_Summary_FK FOREIGN KEY
(
Summary_id
)
REFERENCES Summary
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE UserObjectRelation
ADD CONSTRAINT UserObjectRelation_Object_FK FOREIGN KEY
(
Object_code
)
REFERENCES Object
(
code
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE UserObjectRelation
ADD CONSTRAINT UserObjectRelation_User_FK FOREIGN KEY
(
User_id
)
REFERENCES "User"
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO


-- Oracle SQL Developer Data Modeler Summary Report:
--
-- CREATE TABLE                            17
-- CREATE INDEX                            19
-- ALTER TABLE                             33
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
--
-- DROP DATABASE                            0
--
-- ERRORS                                   0
-- WARNINGS                                 0
